schema:
  dialect: mysql
  datasource: $DB_SUPER_CONNECTION
  dir: schema
  table: migrations_app_hermes
app:
  dialect: mysql
  datasource: $DB_CONNECTION
  dir: app
  database: hermes
  table: migrations_app_hermes